/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CreateReportRouteImport } from './routes/create-report'
import { Route as AiResultRouteImport } from './routes/ai-result'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReportRoute = CreateReportRouteImport.update({
  id: '/create-report',
  path: '/create-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResultRoute = AiResultRouteImport.update({
  id: '/ai-result',
  path: '/ai-result',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/create-report': typeof CreateReportRoute
  '/home': typeof HomeRoute
  '/my-reports': typeof MyReportsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/create-report': typeof CreateReportRoute
  '/home': typeof HomeRoute
  '/my-reports': typeof MyReportsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-result': typeof AiResultRoute
  '/create-report': typeof CreateReportRoute
  '/home': typeof HomeRoute
  '/my-reports': typeof MyReportsRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/supervisor': typeof SupervisorRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-result'
    | '/create-report'
    | '/home'
    | '/my-reports'
    | '/reports'
    | '/review'
    | '/supervisor'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-result'
    | '/create-report'
    | '/home'
    | '/my-reports'
    | '/reports'
    | '/review'
    | '/supervisor'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/ai-result'
    | '/create-report'
    | '/home'
    | '/my-reports'
    | '/reports'
    | '/review'
    | '/supervisor'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiResultRoute: typeof AiResultRoute
  CreateReportRoute: typeof CreateReportRoute
  HomeRoute: typeof HomeRoute
  MyReportsRoute: typeof MyReportsRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SupervisorRoute: typeof SupervisorRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-report': {
      id: '/create-report'
      path: '/create-report'
      fullPath: '/create-report'
      preLoaderRoute: typeof CreateReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-result': {
      id: '/ai-result'
      path: '/ai-result'
      fullPath: '/ai-result'
      preLoaderRoute: typeof AiResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiResultRoute: AiResultRoute,
  CreateReportRoute: CreateReportRoute,
  HomeRoute: HomeRoute,
  MyReportsRoute: MyReportsRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SupervisorRoute: SupervisorRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
